# AUTO-GENERATED from story.v1.json — do not edit manually
# generated by datamodel-codegen:
#   filename:  story.v1.json
#   timestamp: 2026-05-15T23:18:12+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class SchemaVersion(Enum):
    field_1 = '1'


class VocabEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: conint(ge=0)
    word: str
    hiragana: str
    translation: str


class Word(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Sentence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    words: list[Word] = Field(..., min_length=1)
    ruby: list[str | None] | None = None
    vocab_keys: list[conint(ge=0) | None] | None = None
    translation: str | None = None
    grammar: list[conint(ge=0)] | None = None
    audio_url: str | None = None


class NihonNoHonStoryV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion
    id: constr(min_length=1)
    title: constr(min_length=1)
    title_ja: constr(min_length=1)
    language: constr(min_length=1)
    description: constr(min_length=1)
    difficulty: str | None = None
    keywords: list[VocabEntry] | None = None
    grammar: list[str] | None = None
    vocab_supplement: list[VocabEntry] | None = None
    metadata: dict[str, Any] | None = None
    sentences: list[Sentence] = Field(..., min_length=1)
